# Generated vote proof inputs
secret = "12345"
proposal_id = "2"
vote = "1"
nullifier = "14332188545215450039303761686787452173310073856181892036030657610869230302779"
voters_root = "11785482819273298418196146372602982727298252093391523162746898186344366054190"
path_indices = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
siblings = ["0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"]
